Feature/OT2J28-27
alkemyTech/OT228-server pull request #10
Opened 2022-06-20 18:12 UTC by lucas2205

Agregué de mas un template para registro de usuario y después vi que hay otra tarea para hacer eso pero lo dejo hecho.

2022-06-21 18:26 UTC, turcoamado requested changes

2022-06-21 18:26 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/EmailServiceImpl.java
> +            System.out.println("Error sending email");
Esto deberia estar en un log, no en un System.out.

2022-06-21 18:26 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/EmailServiceImpl.java
> +        personalization.setSubject("Welcome to SomosMas ONG!");
Esto podria hacerde de varias maneras, se podria tener una variable de clase para poner el texto alli y pasarle a este metodo directamente esa variable:
`private static final WELCOME_TEXT = "Welcome to SomosMas ONG!";`
o incluso mejor, se podria crear una clase utils que tenga las constantes que vayamos a utilizar en todo lo relativo al envio de mail, porque van a ir apareciendo un par mas

2022-06-21 23:37 UTC, lucas2205 commented on src/main/java/com/alkemy/ong/service/impl/EmailServiceImpl.java
> +        personalization.setSubject("Welcome to SomosMas ONG!");
Buenísimo, gracias por la corrección, ahí lo modifique.

2022-06-22 16:48 UTC, turcoamado approved these changes
Barbaro

2022-06-22 20:45 UTC, merged