Endpoint Listado de Categorías
alkemyTech/OT228-server pull request #16
Opened 2022-06-22 20:36 UTC by Deivyd1995

Servicio y endpoint para traer solo el nombre de todas las categorías. Añadida notación faltante @Service al servicio de comentarios.

2022-06-22 23:45 UTC, turcoamado requested changes

2022-06-22 23:45 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +    CategoryServiceImpl categoryService;
Declarala como private

2022-06-22 23:45 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN')")
Esto esta bien! Pero mejor si los ponemos en donde esta la configuracion de jwt

2022-06-22 23:45 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> +        for (Category category : categories) {
Esto se podria realizar dentro de una funcion lambda, quedaria algo de este estilo:
```
categories.forEach { category ->
    CategoryNameDto categoryNameDto = mapper.map(category, CategoryNameDto.class);
    categoryNameDtos.add(categoryNameDto); 
}
```

Es mas, incluso podrias utilizarlo luego del findAll() como: 
`categoryRepository.findAll().forEach { ... }`

o haciendo uso de la api stream()
```
categoryRepository.findAll()
   .stream()
   .forEach { ... }
```

2022-06-23 00:54 UTC, Deivyd1995 commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN')")
Eso seria en el JwtTokenFilter o lo hago en el springSecurityConfigurator?

2022-06-23 00:55 UTC, Deivyd1995 commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +    CategoryServiceImpl categoryService;
Corregido

2022-06-23 02:42 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN')")
En el **SpringSecurityConfiguration**, fijate que de hecho ya hay un ejemplo, y tiene hasta un comentario

2022-06-23 02:42 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> +    public List<CategoryNameDto> viewAllCategoryNames() {
Si esto te esta funcionando correctamente podes borrar lo que comentaste arriba. No estaba mal eh, simplemente te mencionaba que podias hacer uso de una expresion lambda para agregarle programacion funcional, esto es algo que aparece con java 8 y permite performar mejor algunas cosas

2022-06-26 18:35 UTC, turcoamado approved these changes

2022-06-26 18:36 UTC, turcoamado commented
Te lo mergee yo ya que no tenia conflictos, para agilizar. Perdon la demora en la revision final

2022-06-26 18:36 UTC, merged