feacture/OT2J28-28
alkemyTech/OT228-server pull request #17
Opened 2022-06-23 16:18 UTC by FOMonti

Create Slide Model and Repository

2022-06-23 22:13 UTC, turcoamado requested changes

2022-06-23 22:13 UTC, turcoamado commented on src/main/java/com/alkemy/ong/repository/SlideRepository.java
> +public interface SlideRepository extends JpaRepository<Slide, Long> {
Te falta la annotation @Repository

2022-06-24 12:45 UTC, FOMonti commented
Listo, Anotacion agregada

2022-06-24 22:47 UTC, turcoamado approved these changes

2022-06-24 22:51 UTC, merged