Endpoint update Organization
alkemyTech/OT228-server pull request #18
Opened 2022-06-24 22:08 UTC by lucas2205

Endpoint para actualizar datos publicos de Organization

2022-06-26 18:34 UTC, turcoamado requested changes

2022-06-26 18:34 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImpl.java
> +    OrganizationRepository organizationRepository;
Hacete esta variable de tipo private, lo mismo con la de la linea 19

2022-06-26 18:34 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.BAD_REQUEST,
Aca no seria un BAD REQUEST ya que en realidad la peticion se ejecuto de forma correcta, lo que sucedio es que no encontro ningun registro para el id proporcionado, por lo que seria un NOT FOUND.

Para los mensajes que van hacia la capa de controllers, o sea lo que va a devolver nuestro servicio podriamos implementar un handler y un properties, para no hardcodear los mismos. Te dejo aca unos links para que vayas chusmeando, no hace falta que se implemente ya pero estaria bueno, lo voy a pasar al slack tambien.

https://zetcode.com/spring/messagesource/
https://looksok.wordpress.com/tag/message-properties/

2022-06-27 23:57 UTC, lucas2205 commented on src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImpl.java
> +    OrganizationRepository organizationRepository;
Listo!

2022-06-27 23:58 UTC, lucas2205 commented on src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImpl.java
> +            throw new ResponseStatusException(HttpStatus.BAD_REQUEST,
Buenísimo, ya lo estoy viendo

2022-06-28 02:39 UTC, turcoamado approved these changes
Bien! Lo que te comente de los mensajes lo estaba viendo Fer tambien, asi que podes comunicarte con el cualquier cosa. Chusmeate si queres su PR que alli lo empezo a trabajar

2022-06-28 13:37 UTC, merged