Feacture/ot2j28 24
alkemyTech/OT228-server pull request #19
Opened 2022-06-24 23:01 UTC by FOMonti

Endpoint para registrase + cambios en clases que tiraban errores

2022-06-26 19:10 UTC, turcoamado requested changes
Esta bastante bien todo! Te marque algunas cositas. 
Sacale el propeties o al menos los datos tuyos para la config de la DB

2022-06-26 19:10 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/AuthenticationController.java
> +            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Ese email ya existe");
el mensaje deberia estar en ingles, y en realidad podriamos implementar un handler y un properties para los mensajes, para no tenerlos hardcoded ya que no es una buena practica. Te dejo dos links para que los chusmees, no hace falta hacerlo ahora pero si estaria bueno, se los voy a pasar al slack tambien, y se lo mencione a otro de los chicos en un PR tambien

https://zetcode.com/spring/messagesource/
https://looksok.wordpress.com/tag/message-properties/

2022-06-26 19:10 UTC, turcoamado commented on src/main/java/com/alkemy/ong/security/jwt/JwtUtils.java
> +//		return TOKEN_PREFIX +
Esto que esta comentado borralo

2022-06-26 19:10 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/OrganizationServiceImpl.java
> +        return objectMapper.convertValue(organizationRepository.findById(id), OrganizationDto.class);
Esta bueno el cambio, eliminale el codigo comentado. Y no veo donde se este utilizando el metodo, pero habria que implementarle o aca o donde se este utilizando una exception para cuando no encuentra nada con ese id

2022-06-27 16:31 UTC, FOMonti reviewed
Add MessageHandler;
Delet Coments on OrgnatizationController;
message.properties;
Delet content on aplication.properties

2022-06-28 02:36 UTC, turcoamado requested changes

2022-06-28 02:36 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/AuthenticationController.java
> +    private Users convert(AuthenticactionAuthDto authDto) {
Estos dos metodos que estan aca no van en el controller, los mappers de entity a DTO y  viceversa tienen que ir en el service o en una clase aparte.

2022-06-28 02:36 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/AuthenticationController.java
> +        users.setRole(roleRepository.getById(1L));
Esta no seria la mejor practica, aca deberias buscar el rol  que estas necesitando, si es user entonces habria que buscar por nombre. Porque suponete que se elimina el rol que tiene ese id de la DB y luego se agrega, esto explotaria porque el id 1 ya no existiria

2022-06-28 13:59 UTC, FOMonti reviewed
Listo, con el tema del ROL, se deberia lanzar una excepción? no me había quedado claro.

2022-06-28 16:50 UTC, turcoamado approved these changes
Yo creo que asi como esta por ahora esta bien, digo por ahora porque en el setter dle role en el UserMapper le estas seteando siempre el rol USER, para este requerimiento esta bien, pero quizas mas adelante haya que cambiarlo si es que se utiliza en algun otro lado y no es el rol USER el que se necesita, pero como ahora estas creando un usuario esta bien que por defecto lo meta como USER

2022-06-29 16:15 UTC, merged