Category creation endpoint. Feature/OT2J28-42
alkemyTech/OT228-server pull request #21
Opened 2022-06-26 02:24 UTC by RobertoLatorraca

2022-06-26 20:36 UTC, turcoamado reviewed
Esta bueno!! Lo unico que le agregaria yo seria chequear que el nombre no tiene caracteres especiales ni numeros, o sea, tiene solo letras. Supongo que a eso se refiere la tarjeta cuando dice que hay que validar que sea string. Mas que nada para que pispeen lo que son las expresiones regulares. Y de paso te dejo dos links que te pueden ayudar a chequear una RegEx:
https://www.regexpal.com/21
https://regex101.com/r/zfCKel/2

2022-06-26 20:36 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +	protected static final String CATEGORIES = "/categories";
Esta linea la podes agregar en la annotation RequestMapping quizas sin estar dentro de una variable, no esta mal y aca realmente no se cual es la mejor practica, supongo que lo sabes porque es exactamente lo mismo, te quedaria como: @RequestMapping("/categories")
No hace falta que lo modifiques, solo te lo menciono.

2022-06-26 20:36 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> +		return ModelMapperFacade.map(
Esta buena esta implementacion de los mappers! Ya que el facade quedo bien generico

2022-06-26 20:37 UTC, turcoamado requested changes
Esta bueno!! Lo unico que le agregaria yo seria chequear que el nombre no tiene caracteres especiales ni numeros, o sea, tiene solo letras. Supongo que a eso se refiere la tarjeta cuando dice que hay que validar que sea string. Mas que nada para que pispeen lo que son las expresiones regulares. Y de paso te dejo dos links que te pueden ayudar a chequear una RegEx:
https://www.regexpal.com/21
https://regex101.com/r/zfCKel/2

2022-06-27 03:31 UTC, RobertoLatorraca commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +	protected static final String CATEGORIES = "/categories";
Para todas las propiedades que de alguna forma configuran a la clase utilizo variables ubicadas al principio. De esta forma en caso de que el código sea extenso tengo acceso a estas propiedades sin necesidad de navegar por las líneas. Por otro lado también me obligan a definirlas para valores numéricos y me evita generar números mágicos (malas prácticas). En este caso dado que es una sola línea no parece tener mucho sentido, lo hago ya por costumbre.

2022-06-27 03:43 UTC, RobertoLatorraca commented
Resolvi los conflictos entre este branch y develop, sin tocar ninguna línea del código de mis compañeros.

2022-06-27 15:46 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +	protected static final String CATEGORIES = "/categories";
> Para todas las propiedades que de alguna forma configuran a la clase utilizo variables ubicadas al principio. De esta forma en caso de que el código sea extenso tengo acceso a estas propiedades sin necesidad de navegar por las líneas. Por otro lado también me obligan a definirlas para valores numéricos y me evita generar números mágicos (malas prácticas). En este caso dado que es una sola línea no parece tener mucho sentido, lo hago ya por costumbre.

Si y esta perfecto lo que haces! Es una muy buena practica, justametne iba al caso puntual de que es una sola linea y no se vuelva a utilizar, pero por eso tampoco te dije que lo modifiques. Me parece muy buenos los principios que estas utilizando a la hora de codificar

2022-06-27 15:47 UTC, turcoamado approved these changes
Buenisimo Robert!

2022-06-27 16:55 UTC, merged