Add News EndPoint
alkemyTech/OT228-server pull request #27
Opened 2022-06-28 22:06 UTC by lucas2205

No agregue lo del messageHandler por que estaba esperando que el compañero haga merge de lo que el habia armado

2022-06-29 23:06 UTC, turcoamado approved these changes
Tenes un archivo agregado que creo se te paso, es de configuracion. O si lo agregaste a proposito explicame porque no lo entendi.
Te lo dejo como aprobado pero sacale eso antes de hacer el merge

2022-06-29 23:06 UTC, turcoamado commented on src/main/java/com/alkemy/ong/exception/ResourceNotFoundException.java
> +public class ResourceNotFoundException extends RuntimeException{
Esto lo vi en otro PR, muy bueno, me gusta la creacion de esta clase! Luego hay que modificar el tema de las variables estaticas (que aca estan bien) al properties de mensajes

2022-06-29 23:06 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/NewsServiceImpl.java
> +        Category category = categoryRepository.findById(newsDto.getCategory().getId()).orElseThrow(() -> new ResourceNotFoundException("That category does not exists"));
muy bueno el uso de la expresion lambda! Queda pendiente para luego de su implementacion mover el string al message.properties

2022-06-29 23:06 UTC, turcoamado commented on src/main/resources/.LCKapplication.properties~
> +C:\Users\lucas\Documents\NetBeansProjects\AceleracionAlkemy\OT228-server\src\main\resources\application.properties
Este archivo se te paso!

2022-06-29 23:15 UTC, turcoamado requested changes
Te lo paso a Request Changes porque ya se implemento el handler de mensajes, asi que modificate eso en el service y estamos. Ah y saca el archivo de config

2022-06-30 16:55 UTC, lucas2205 commented
Listo los cambios!

2022-07-01 02:19 UTC, turcoamado approved these changes
Buenisimo

2022-07-01 02:20 UTC, turcoamado commented
Lo mergeo yo así queda

2022-07-01 02:20 UTC, merged