Category update endpoint. Feature/OT2J28-43
alkemyTech/OT228-server pull request #28
Opened 2022-06-29 01:00 UTC by RobertoLatorraca

2022-06-29 23:11 UTC, turcoamado requested changes

2022-06-29 23:11 UTC, turcoamado commented on src/main/java/com/alkemy/ong/exception/NotFoundException.java
> +public class NotFoundException extends RuntimeException {
Esto lo vi en otro PR, muy bueno, me gusta la creacion de esta clase! Lo hay que modificar el tema de las variables estaticas (que aca estan bien) al properties de mensajes, ya esta implementado. Ponganse de acuerdo con esta clase para que la toque uno solo y asi no se hacen lio

2022-06-29 23:11 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/CategoryServiceImpl.java
> +	public CategoryDto update(CategoryDto categoryDto) {
Muy bueno el uso de las expresiones lambda Robert! Pasate los mensajes al properties para hacer uso del handler que ya implemento Fer, asi lo vamos dejando prolijito.

2022-06-30 18:06 UTC, RobertoLatorraca commented on src/main/java/com/alkemy/ong/exception/NotFoundException.java
> +public class NotFoundException extends RuntimeException {
No utilicé el MessageHandler en esta clase todavia debido a que por un lado tengo que inyectar el Bean de mensajes y al mismo tiempo en los constructores de clase la primer línea que se ejecuta siempre es `super()` y en este caso estoy enviando el mensaje al constructor de la clase padre `super(String message)`. Necesito verlo con más detenimiento como lo resuelvo y no quise seguir atrasando el merge de este pull request.

2022-07-01 02:24 UTC, turcoamado approved these changes
Bien! Entiendo lo que me decís. Estaría OK entonces, muevo la tarjeta a DONE a pesar de que el merge se demore unas horas por resolución de conflictos

2022-07-01 04:27 UTC, merged