Endpoint Update News
alkemyTech/OT228-server pull request #32
Opened 2022-07-01 00:34 UTC by Sangelp8833

2022-07-01 02:50 UTC, turcoamado requested changes
Fijate que si modificas el endpoint enviando directamente el DTO en lugar de un map la lógica del service te queda mucho mas sencilla

2022-07-01 02:50 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/NewsServiceImpl.java
> +        if (news.isEmpty()){
Por que le cambiaste el isPresent(), iba bien con eso

2022-07-01 02:50 UTC, turcoamado commented on src/main/java/com/alkemy/ong/controller/NewsController.java
> +    public ResponseEntity<?> updateNews(@RequestBody Map<String, Object> update, @PathVariable Long newsId){
Te esta faltando la annotation @Valid, y para el path alcanzaría con /{id}
También te la estas complicando con la firma del endpoint, podrías hacer algo como
`public ResponseEntity<?> updateNews(@RequestBody NewsDto newsDto, @Valid @PathVariable Long newsId){`
y en vez de un map le pasas directamente el DTO al service

2022-07-01 02:50 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/NewsServiceImpl.java
> +            update.forEach((key,value)->{
Esto esta bien pensado, pero enviando el DTO te queda mucho mas simple

2022-07-01 12:47 UTC, Sangelp8833 commented on src/main/java/com/alkemy/ong/controller/NewsController.java
> +    public ResponseEntity<?> updateNews(@RequestBody Map<String, Object> update, @PathVariable Long newsId){
Perfecto Yamil, corregido.

2022-07-02 15:46 UTC, turcoamado approved these changes

2022-07-02 22:21 UTC, merged