Feature/OT2J28-78 DELETE COMMENT
alkemyTech/OT228-server pull request #58
Opened 2022-07-18 03:55 UTC by lucas2205

2022-07-19 00:11 UTC, turcoamado requested changes

2022-07-19 00:11 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/CommentsServiceImpl.java
> +            throw new BadRequestException("");
Esta deberia ser una exception de otro tipo, se podria crear una para indicar que no se tienen permisos para eliminar el comentario

2022-07-19 00:11 UTC, turcoamado commented on src/main/java/com/alkemy/ong/service/impl/CommentsServiceImpl.java
> +        return (principal instanceof UserDetails)
me gusta como resolviste esta expresion aca

2022-07-20 14:32 UTC, lucas2205 commented on src/main/java/com/alkemy/ong/service/impl/CommentsServiceImpl.java
> +            throw new BadRequestException("");
Listo!

2022-07-21 01:03 UTC, turcoamado approved these changes

2022-07-21 22:46 UTC, merged