Created Model-Member
alkemyTech/OT228-server pull request #9
Opened 2022-06-17 15:00 UTC by FOMonti

Creando modelo member.

2022-06-17 18:05 UTC, turcoamado requested changes
El modelo esta bien, pero segun el ticket de Jira te falta tambien el repositorio

2022-06-17 18:05 UTC, turcoamado commented on src/main/java/com/alkemy/ong/model/Member.java
> +@SQLDelete(sql = "UPDATE members SET soft_delete = true WHERE id=?")
para simplificar yo utilizaria un nombre simple, no se un _deleted_ por ejemplo. Ojo no esta mal, es una cosa mia nomas, no es necesario que lo modifiques. Si lo haces tene en cuenta que hay que cambiar tambien la linea 51 donde le asignas el nombre a la columna en la DB

2022-06-23 12:58 UTC, FOMonti reviewed
Correcion de modelo y creando repositorio

2022-06-23 22:11 UTC, turcoamado approved these changes

2022-06-24 22:52 UTC, merged